title:            crosswalkr
tagline:          'R package'
description:      'Rename and Encode Data Frames Using External Crosswalk Files'
github:		  https://github.com/btskinner/crosswalkr
version:	  0.1.1
url:		  http://btskinner.me
baseurl: 	  "/crosswalkr"

highlighter:      rouge
permalink:        pretty


